name: cocoon
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/home_bg.png
    - assets/images/luna.png
    - assets/images/kokoro_bg.png
    - assets/images/emotion_anxiety.png
    - assets/images/emotion_peace.png
    - assets/images/emotion_lonely.png
    - assets/images/emotion_tired.png
    - assets/images/emotion_angry.png
    
